plot(function(x) x, 0, 1)
x <- seq(.01, .99, by = .01)
y <- arm::invlogit(car::logit(x) + .5)
lines(y~x, ylim = c(0,1), col = 2, lty = 2)
abline(lm(y ~ x), col = 2)
y <- arm::invlogit(car::logit(x) + 1)
lines(y ~ x, ylim = c(0,1), col = 3, lty = 2)
abline(lm(y ~ x), col = 3)
y <- arm::invlogit(car::logit(x) + 1.5)
lines(y ~ x, ylim = c(0,1), col = 4, lty = 2)
abline(lm(y ~ x), col = 4)
y <- arm::invlogit(car::logit(x) + 2)
lines(y ~ x, ylim = c(0,1), col = 5, lty = 2)
abline(lm(y ~ x), col = 5)

